apiVersion: v1
entries:
  consumer-helm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-09-13T17:07:51.049029+03:00"
    description: A Helm chart for Kubernetes
    digest: 0d8aa6e51aa443f607f0e5d8f995f10eb4f338c7d6de5760ff68433b1f6795a8
    name: consumer-helm
    type: application
    urls:
    - consumer-helm-0.1.0.tgz
    version: 0.1.0
generated: "2022-09-13T17:07:51.048126+03:00"
